# Generated by Django 4.1.3 on 2022-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_despesas_despesa_rename_receitas_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='data',
        ),
        migrations.AddField(
            model_name='despesa',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='despesa',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.FloatField(default='0.00'),
        ),
    ]
