# Generated by Django 4.1.3 on 2022-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_remove_despesa_data_remove_receita_data_despesa_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('a', 'Alimentação'), ('s', 'Saúde'), ('m', 'moradia'), ('t', 'Transporte'), ('e', 'Educação'), ('l', 'Lazer'), ('i', 'Imprevistos'), ('o', 'Outras')], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='receita',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=2),
        ),
    ]
