# Generated by Django 4.1.3 on 2022-11-04 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_despesa_categoria_alter_despesa_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='mes',
        ),
        migrations.AddField(
            model_name='receita',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
