# Generated by Django 4.1.3 on 2022-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_remove_receita_ano_remove_receita_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data',
        ),
        migrations.AddField(
            model_name='receita',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=2),
        ),
    ]
