# Generated by Django 4.1.3 on 2022-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.FloatField(default='0.00')),
                ('categoria', models.CharField(choices=[('a', 'Alimentação'), ('s', 'Saúde'), ('m', 'moradia'), ('t', 'Transporte'), ('e', 'Educação'), ('l', 'Lazer'), ('i', 'Imprevistos'), ('o', 'Outras')], default='o', max_length=1, null=True)),
                ('data', models.DateField()),
            ],
        ),
    ]
