# Generated by Django 3.2.16 on 2022-11-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, unique_for_month='data'),
        ),
    ]
